
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - ARM64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.42.34433/bin/Hostarm64/arm64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Compilateur d'optimisation Microsoft (R) C/C++ version 19.42.34435 pour ARM64
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.42.34435.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Programmation/all_project_sync/archimed/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1243 (message)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Remarque : inclusion du fichier :  C:\\Programmation\\all_project_sync\\archimed\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Remarque : inclusion du fichier :  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Programmation/all_project_sync/archimed/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6st90n"
      binary: "C:/Programmation/all_project_sync/archimed/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6st90n"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:ARM64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Programmation/all_project_sync/archimed/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6st90n'
        
        Run Build Command(s): C:/Users/mehdi/AppData/Local/Programs/CLion/bin/ninja/win/aarch64/ninja.exe -v cmTC_673a6
        [1/2] C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1442~1.344\\bin\\HOSTAR~1\\arm64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Ob0 /Od /RTC1 -MDd -Zi /showIncludes /FoCMakeFiles\\cmTC_673a6.dir\\CMakeCCompilerABI.c.obj /FdCMakeFiles\\cmTC_673a6.dir\\ /FS -c C:\\Users\\mehdi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\aarch64\\share\\cmake-3.30\\Modules\\CMakeCCompilerABI.c
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Users\\mehdi\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\aarch64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_673a6.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\arm64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\arm64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1442~1.344\\bin\\HOSTAR~1\\arm64\\link.exe /nologo CMakeFiles\\cmTC_673a6.dir\\CMakeCCompilerABI.c.obj  /out:cmTC_673a6.exe /implib:cmTC_673a6.lib /pdb:cmTC_673a6.pdb /version:0.0 /machine:ARM64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/PROGRA~1/MICROS~3/2022/COMMUN~1/VC/Tools/MSVC/1442~1.344/bin/HOSTAR~1/arm64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/Users/mehdi/AppData/Local/Programs/CLion/bin/cmake/win/aarch64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "C:/PROGRA~1/MICROS~3/2022/COMMUN~1/VC/Tools/MSVC/1442~1.344/bin/HOSTAR~1/arm64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.42.34435.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
